name: Testing

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: us-east-1

    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.4.1
      with:
        access_token: ${{ github.token }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Create Virtualenv
      run: |
        python -m venv env
        source env/bin/activate
    - name: install dependencies for deployment
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest


    - name: Test with pytest
      run: |
        pytest -s -v tests
